export const ROOT_PATH = '/'
export const LOGIN_PATH = '/login'
export const LOGOUT_PATH = '/logout'
export const BANKING_PATH = '/banking'
export const CONFIGS_PATH = '/configs'
export const BACKOFFICE_PATH = '/backoffice'
